### ISSUE TITLE
Chrome on Android Tracking Issue

### ISSUE THREAD

**Issue by GlenDC** [ulixee/hero#304]
- [x] fail default-browser-emulator for android (mobile) targets:
     - As part of the effort on supporting mobile browsers natively to unblocked, a first good step would be to make sure the default browser emulator does not accept mobile targets (e.g. android chrome).
- [ ] activate mobile user agent strings in unblocked/real-user-agents
- [ ] collaborate on a PoC mobile browser emulator plugin:
    - To facilitate this collaboration I created a repository already on which we will push our work for this Proof of Concept (Poc): https://github.com/OTA-Insight/default-mobile-browser-emulator
    - [ ] publish PoC project to NPM
    - [ ] have a (private) project make use of this plugin and report on its usage + iterate while using it
- [ ] copy portions of the default emulator into chrome for android emulator to emulate user agent and activate touch
  -  This is where an emulator says it can handle a user agent https://github.com/ulixee/unblocked/blob/d468b4aba38b0f3cd800b1dc241586265ff13a38/plugins/default-browser-emulator/index.ts#L226
- [ ] study the headers/tls/tcp/etc in double-agent profiles
- [ ] automatically generate double-agent profiles based on our findings
- [ ] add missing evasion techniques
- [ ] refactor common evasion technique functionality
